### ISSUE TITLE
missing plugin configuration prevents agent start

### ISSUE THREAD

**Issue by tgross** [hashicorp/nomad-driver-exec2#18]
If the `plugin` block is missing from the agent configuration for this plugin but the plugin binary is present in the plugin directory, Nomad will fail fingerprinting and the agent will not start.

> 2024-05-10T11:35:37.795-0400 [WARN]  agent.plugin_loader: plugin not referenced in the agent configuration file, future versions of Nomad will not load this plugin until the agent configuration is updated: plugin_dir=/home/tim/ws/nomad/etc/plugins plugin=nomad-driver-exec2
> 2024-05-10T11:35:37.810-0400 [INFO]  agent.plugin_loader: plugin process exited: plugin_dir=/home/tim/ws/nomad/etc/plugins plugin=/home/tim/ws/nomad/etc/plugins/nomad-driver-exec2 id=284674
> 2024-05-10T11:35:37.821-0400 [ERROR] agent: error starting agent:
  error=
  | failed to create plugin loader: failed to initialize plugin loader: parsing plugin configurations failed: 1 error occurred:
  | \t* plugin "exec2" (driver): failed to parse config:  Missing required argument: The argument "unveil_paths" is required, but no definition was found.
  |

Note that in https://github.com/hashicorp/nomad/pull/19189 we added a warning log to Nomad's plugin loader that indicated that missing plugin configurations would be deprecated. But the warning says only that the plugin will not be loaded, not that the agent won't be started.

**Comment by shoenig** [comment]
Fixed in #26
