### ISSUE TITLE
release: use CRT to publish releases 

### ISSUE THREAD

**Issue by shoenig** [hashicorp/nomad-driver-exec2#4]

**Comment by david-yu** [comment]
It would be nice if we could assume the default `/opt/nomad/data` dir for installs on nomad for plugin_dir see https://github.com/hashicorp/nomad/blob/main/.release/linux/package/etc/nomad.d/nomad.hcl#L6. 

Given the assumption, it would be great to also be able to install via yum or apt packaging so one could easily install `nomad` and `exec2` using something like

```
$ apt-get install nomad nomad-driver-exec2

```
