### ISSUE TITLE
APT install does not enable the plugin

### ISSUE THREAD

**Issue by EtienneBruines** [hashicorp/nomad-driver-exec2#43]
When installing `nomad` and `nomad-driver-exec2` using apt (on Ubuntu), the `exec2` plugin does not automatically get detected.

I manually had to do

```bash
ln -s /usr/bin/nomad-driver-exec2 /opt/nomad/data/plugins/nomad-driver-exec2
```

Would it make sense to have the installer do this automatically?

**Comment by tgross** [comment]
Hi @EtienneBruines this was fixed in https://github.com/hashicorp/nomad-driver-exec2/pull/39 but we haven't shipped a release with that fix yet.
