### ISSUE TITLE
permissions errors with unveil on task directory

### ISSUE THREAD

**Issue by ChrisAdkin8** [hashicorp/nomad-driver-exec2#51]
When I run the following job with Nomad 1.7.7 I get the following written to standard output which is the bahaviour I expect:

Hello, World!
Hello, World!
Hello, World!

Job spec:

```
job "java-compile-run" {
  group "java-group" {
    task "compile-and-run" {
      driver = "exec2"
      
      # CHANGE THIS to match your user
      user   = "ubuntu"
      
      config {
        command = "/bin/bash"
        args    = [
          "-c",
          "javac HelloWorld.java && java HelloWorld"
        ]
        
        # CHANGE this -- I didn't have this path
        unveil = [ "r:/usr/lib/jvm/java-21-openjdk-amd64/conf/security/java.security" 
                  ,"rwc:." ]
      }
      
      artifact {
        source      = "https://raw.githubusercontent.com/ChrisAdkin8/Nomad-Tutorials/main/jobs/java/HelloWorld.java"
        destination = "."
      }
       
      resources {
        cpu    = 500
        memory = 256
      }
      env {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        PATH      = "${JAVA_HOME}/bin:${PATH}"
      }
    }
  }
```

However, when I change the job spec to (Java code written to local/java):

```
job "java-compile-run" {
  group "java-group" {
    task "compile-and-run" {
      driver = "exec2"
      
      # CHANGE THIS to match your user
      user   = "ubuntu"
      
      config {
        command = "/bin/bash"
        args    = [
          "-c",
          "cd local/java && javac HelloWorld.java && java HelloWorld"
        ]
        
        # CHANGE this -- I didn't have this path
        unveil = [ "r:/usr/lib/jvm/java-21-openjdk-amd64/conf/security/java.security" 
                  ,"rwc:local/java" ]
      }
      
      artifact {
        source      = "https://raw.githubusercontent.com/ChrisAdkin8/Nomad-Tutorials/main/jobs/java/HelloWorld.java"
        destination = "local/java"
      }
       
      resources {
        cpu    = 500
        memory = 256
      }
      env {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        PATH      = "${JAVA_HOME}/bin:${PATH}"
      }
    }
  }
```

I get the following written to stderr:

HelloWorld.java:1: error: error while writing HelloWorld: /opt/nomad/data/alloc/f7da9567-dcc6-8f08-bc01-da47f968d738/compile-and-run/local/java/HelloWorld.class
public class HelloWorld {
       ^
1 error
HelloWorld.java:1: error: error while writing HelloWorld: /opt/nomad/data/alloc/f7da9567-dcc6-8f08-bc01-da47f968d738/compile-and-run/local/java/HelloWorld.class
public class HelloWorld {
       ^
1 error
HelloWorld.java:1: error: error while writing HelloWorld: /opt/nomad/data/alloc/f7da9567-dcc6-8f08-bc01-da47f968d738/compile-and-run/local/java/HelloWorld.class
public class HelloWorld {
       ^
1 error

When I change the job code to get permissions on local/java, I get:

`drwxr-xr-x 2 0 0 4096 Aug 26 10:02 local/java`

Note that I am running Nomad 1.77 on AWS EC2 instances with Ubuntu 22.04 LTS

**Comment by tgross** [comment]
@ChrisAdkin8 you shouldn't need to unveil the Nomad task/alloc/secrets directories at all (and I'm pretty sure the unveil path you're using `local/java` is a path in the host environment, so not relative to the working directory). It's also not clear what you mean by "When I change the job code to get permissions on local/java"?

**Comment by ChrisAdkin8** [comment]
@tgross when the destination is set to '.' in the artifact block the code works, when the destination is set to anything other than the root of the task directory, because whatever this is appears not to inherit permissions from the task root directory, the compilation of the Java code fails in this case. Does this help clarify things ?.

**Comment by tgross** [comment]
@ChrisAdkin8 in addition to reproducing the failure when writing explicitly to the task dir, I was not able to reproduce it working with `.` set as a destination. Running on an ubuntu VM with OpenJDK21 installed, I used the following jobspec:

<details><summary>jobspec</summary>

```hcl
job "example" {

  type = "batch" # needs to be batch because it's supposed to exit

  group "java-group" {
    task "compile-and-run" {
      driver = "exec2"
      user   = "ubuntu"

      config {
        command = "/bin/bash"
        args    = [
          "-c",
          "cd ${NOMAD_TASK_DIR}/java && javac HelloWorld.java && java HelloWorld"
        ]

        unveil = [
          "r:/usr/lib/jvm/java-21-openjdk-amd64/conf/security/java.security",
          "rwc:${NOMAD_TASK_DIR}/java",
        ]
      }

      artifact {
        # URL for my local artifact server
        source      = "http://continuity.local/HelloWorld.java"
        destination = "local/java"
      }

      resources {
        cpu    = 500
        memory = 256
      }

      env {
        JAVA_HOME = "/usr/lib/jvm/java-21-openjdk-amd64"
        PATH      = "${JAVA_HOME}/bin:${PATH}"
      }

    }
  }
}
```

</details>

With the following file in my artifact server:

```java
public class HelloWorld {

        public static void main(String args[]){
                System.out.println("Hello World");
        }
}
```

With this jobspec or one where I remove the unnecessary unveil for the task dir, I get the following error:

```
$ nomad alloc logs -stderr 4e48
HelloWorld.java:1: error: error while writing HelloWorld: /var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/local/java/HelloWorld.class
public class HelloWorld {
       ^
1 error
```

If I swap out the destination to `.` and add an unveil path `rwc:.` and remove the `cd`, I get the following error instead:

```
$ nomad alloc logs -stderr 5c7e
error: error reading HelloWorld.java; /var/nomad/data/alloc/5c7e6278-93ad-4d7a-ea69-1d8830b6f59a/compile-and-run/HelloWorld.java
1 error
```

Note the following logs, which show the unveil paths and should cover the task directory:

> 2024-09-25T11:28:24.334-0400 [INFO]  client.driver_mgr.nomad-driver-exec2: exec2 runner: driver=exec2 unveil_defaults=true @module=exec2 oom_score_adj=0 unveil_paths=[rwxc:/var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/local, rwxc:/var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/alloc, rwxc:/var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/secrets, rwxc:/var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/tmp, r:/usr/lib/jvm/java-21-openjdk-amd64/conf/security/java.security] args=[-c, "cd /var/nomad/alloc_mounts/4e48f173-2982-a032-f66e-e2e56cdcf3f8-compile-and-run/local/java && javac HelloWorld.java && java HelloWorld"] cmd=/bin/bash timestamp=2024-09-25T11:28:24.328-0400

Going to ping @shoenig here to see if he has thoughts.
