### ISSUE TITLE
documentation bug regarding paths used in the artifact block

### ISSUE THREAD

**Issue by ChrisAdkin8** [hashicorp/nomad-driver-exec2#52]
It appears that when using an artifact block in conjunction with the exec2 task drive the destination path is always relative to the allocation working directory, the documentation here https://developer.hashicorp.com/nomad/plugins/drivers/exec2 does not mention this, can this please be added.

**Comment by tgross** [comment]
It should be relative to the _allocation_ working directory, isn't it? As documented here: https://developer.hashicorp.com/nomad/docs/job-specification/artifact#destination

**Comment by ChrisAdkin8** [comment]
As stated, the fact that the path is relative to the root of the task directory is stated in the documentation for the artifact block, please close this issue.

**Comment by jrasell** [comment]
Thanks for the response @ChrisAdkin8 and I'll go ahead and close this issue out.
